name: 'Install Linux Dependencies'
description: 'Installs Ubuntu GTK and Python Dependencies'
runs:
  using: composite
  steps:
    - run: >
        sudo apt-get update -q && sudo apt-get install
        --no-install-recommends -y xvfb python3-dev python3-gi upx
        python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev libcairo2-dev
        libgtksourceview-4-dev
      shell: bash
